name: rm-gym-survey
services:
- name: web
  source_dir: /
  github:
    repo: YOUR_GITHUB_REPO
    branch: main
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    value: ${DATABASE_URL}
  - key: GOOGLE_SHEET_ID
    value: ${GOOGLE_SHEET_ID}